# Generated by Django 3.1.2 on 2020-10-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailinglistSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Enter your email here.', max_length=254, unique=True)),
                ('name', models.CharField(help_text='What should we call you?', max_length=254)),
            ],
            options={
                'verbose_name': 'Mailing List Enteries',
            },
        ),
    ]
