# Generated by Django 3.1.2 on 2020-12-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20201227_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkIntelligence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_visited', models.CharField(max_length=128)),
                ('platform_on', models.CharField(max_length=128)),
                ('visited_from', models.URLField()),
            ],
        ),
    ]
